/// Helper module used to parse XML documentation files generated by .NET compilers.
[<RequireQualifiedAccess>]
module DocTestDotNet.DocumentationParser

open System.Xml

val parseTestsFromReader : source: XmlReader -> ResizeArray<DocumentationTest>
