/// Helper module used to parse XML documentation files generated by .NET compilers.
[<RequireQualifiedAccess>]
module DocTestDotNet.Xml.DocumentationParser

open System.Collections.Generic
open System.Xml

val parseTestsFromReader : reader: XmlReader -> ParserOutput

val parseTestsFromString : xml: string -> ParserOutput
